### ISSUE TITLE
Problem with doc generation

### ISSUE THREAD

**Issue by amadanmath** [KWARC/KAT#64]
```
$ grunt jsdoc-ng:kat
Running "jsdoc-ng:kat" (jsdoc-ng) task
NOM DESC KWARC Annotation Tool: An Annotation Tool for STEM Documents. 
Warning: Arguments to path.join must be strings Use --force to continue.

Aborted due to warnings.
```

It might (or might not) have something to do with usrz/javascript-grunt-jsdoc-ng#3.

**Comment by tkw1536** [comment]
@amadanmath I haven't had the problem myself, but that is probably because I have an older version of the npm dependencies installed. I have temporarily disabled the docs build target (which only builds the API docs) and will look into it in more detail on monday morning. 

/cc @LiftnLearn @kohlhase

**Comment by tkw1536** [comment]
I could not find a proper solution for the issues, so I have switched over to using a slightly different jsdoc template. I have tested on a blank machine and have updated the instructions in the README. To update cleanly, do: 

````bash
cd /path/to/clone/of/KAT/

# Cleanup old versions, ensure the working directory is clean
rm -r node_modules
npm uninstall -g grunt 
git reset --hard

# Pull and install cleanly
git pull
npm install -g grunt
npm install .
```

/cc @LiftnLearn
